//Auth 
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN.FAIL'
export const LOGOUT = 'LOGOUT'
export const LOAD_USER = 'LOAD_USER'

//Accounts
export const FETCH_ACCOUNTS_PENDING = 'FETCH_ACCOUNTS_PENDING'
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS'
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL'

// export const FETCH_ACCOUNT_DETAILS_PENDING = 'FETCH_ACCOUNTS_DETAILS_PENDING'
// export const FETCH_ACCOUNTS_DETAILS_SUCCESS = 'FETCH_ACCOUNTS_DETAILS_SUCCESS'
// export const FETCH_ACCOUNTS_DETAILS_FAIL = 'FETCH_ACCOUNT_DETAILS_FAIL'

export const UPDATE_ACCOUNT_DETAILS_PENDING = 'UPDATE_ACCOUNT_DETAILS_PENDING'
export const UPDATE_ACCOUNT_DETAILS_SUCCESS = 'UPDATE_ACCOUNT_DETAILS_SUCCESS'
export const UPDATE_ACCOUNT_DETAILS_FAIL = 'UPDATE_ACCOUNT_DETAILS_FAIL'

export const DELETE_ACCOUNT_PENDING = 'DELETE_ACCOUNT_PENDING'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'

export const SET_ACCOUNTS = 'SET_ACCOUNTS'