export const dummyTrades = [
    {
        _id: 'a1',
        symbol: 'MSFT',
        outcome: 'win',
        amount: '125.00',
        date: '9/11/20',
        description: 'First trade of the day',
        strategy: 'Orderflow',
        accountId: '11',
        userId: '1',
        createdAt: '14:37',
    },
    {
        _id: 'a2',
        symbol: 'AMZN',
        outcome: 'win',
        amount: '145.25',
        date: '9/11/20',
        description: 'Yuge win',
        strategy: 'Orderflow',
        accountId: '11',
        userId: '1',
        createdAt: '14:38',
    },
    {
        _id: 'a3',
        symbol: 'AAPL',
        outcome: 'loss',
        amount: '-65.50',
        date: '9/11/20',
        description: 'Small loss',
        strategy: 'Orderflow',
        accountId: '11',
        userId: '1',
        createdAt: '15:32',
    },
    {
        _id: 'a3',
        symbol: 'AAPL',
        outcome: 'loss',
        amount: '-65.50',
        date: '9/11/20',
        description: 'Small loss',
        strategy: 'Orderflow',
        accountId: '11',
        userId: '2',
        createdAt: '15:32',
    },
];
