// Request and Load screen
export const REQUEST_START = 'REQUEST_START' 
export const REQUEST_END = 'REQUEST_END' 


export const POPULATE_USER = 'POPULATE_USER';
export const POPULATE_USER_FAIL = 'POPULATE_USER_FAIL';
//Auth 
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN.FAIL'
export const LOGOUT = 'LOGOUT'
export const LOAD_USER = 'LOAD_USER'

//Accounts
export const FETCH_ACCOUNTS_PENDING = 'FETCH_ACCOUNTS_PENDING'
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS'
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL'
export const LOAD_ACCOUNTS_SUCCESS = 'LOAD_ACCOUNTS_SUCCESS'
export const LOAD_ACCOUNTS_FAIL = 'LOAD_ACCOUNTS_FAIL'


export const LOAD_ACCOUNTS = 'SET_ACCOUNTS'

export const FETCH_STRATEGIES_PENDING = 'FETCH_STRATEGIES_PENDING'
export const FETCH_STRATEGIES_SUCCESS = 'FETCH_STRATEGIES_SUCCESS'
export const FETCH_STRATEGIES_FAIL = 'FETCH_STRATEGIES_FAIL'

export const LOAD_STRATEGIES_SUCCESS = 'LOAD_STRATEGIES_SUCCESS'