// Request and Load screen
export const REQUEST_START = 'REQUEST_START' 
export const REQUEST_END = 'REQUEST_END' 

//Auth 
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN.FAIL'
export const LOGOUT = 'LOGOUT'
export const LOAD_USER = 'LOAD_USER'

//Accounts
export const FETCH_ACCOUNTS_PENDING = 'FETCH_ACCOUNTS_PENDING'
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS'
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL'

// export const FETCH_ACCOUNT_DETAILS_PENDING = 'FETCH_ACCOUNTS_DETAILS_PENDING'
// export const FETCH_ACCOUNTS_DETAILS_SUCCESS = 'FETCH_ACCOUNTS_DETAILS_SUCCESS'
// export const FETCH_ACCOUNTS_DETAILS_FAIL = 'FETCH_ACCOUNT_DETAILS_FAIL'

export const UPDATE_ACCOUNT_DETAILS_PENDING = 'UPDATE_ACCOUNT_DETAILS_PENDING'
export const UPDATE_ACCOUNT_DETAILS_SUCCESS = 'UPDATE_ACCOUNT_DETAILS_SUCCESS'
export const UPDATE_ACCOUNT_DETAILS_FAIL = 'UPDATE_ACCOUNT_DETAILS_FAIL'

export const DELETE_ACCOUNT_PENDING = 'DELETE_ACCOUNT_PENDING'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'

export const LOAD_ACCOUNTS = 'SET_ACCOUNTS'

export const FETCH_STRATEGIES_PENDING = 'FETCH_STRATEGIES_PENDING'
export const FETCH_STRATEGIES_SUCCESS = 'FETCH_STRATEGIES_SUCCESS'
export const FETCH_STRATEGIES_FAIL = 'FETCH_STRATEGIES_FAIL'
// export const UPDATE_STRATEGY_DETAILS_PENDING
// export const UPDATE_STRATEGY_DETAILS_SUCCES
// export const UPDATE_STRATEGY_DETAILS_FAIL
// export const DELETE_STRATEGY_PENDING
// export const DELETE_STRATEGY_SUCCESS
// export const DELETE_STRATEGY_FAIL
export const LOAD_STRATEGIES = 'LOAD_STRATEGIES'