// Request and Load screen
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_END = 'REQUEST_END';

export const POPULATE_USER = 'POPULATE_USER';
export const POPULATE_USER_FAIL = 'POPULATE_USER_FAIL';
//Auth

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN.FAIL';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER = 'LOAD_USER';

//Accounts

export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL';

export const FETCH_STRATEGIES_SUCCESS = 'FETCH_STRATEGIES_SUCCESS';
export const FETCH_STRATEGIES_FAIL = 'FETCH_STRATEGIES_FAIL';

export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const ADD_ACCOUNT_FAIL = 'ADD_ACCOUNT_FAIL';
